### ISSUE TITLE
Can runCommand be a Promise?

### ISSUE THREAD

**Issue by vvo** [Mechazawa/minidrone-js#1]
I was wondering if runCommand could be returning a Promise when the command is finished being applied. WDYT?

What's the right way to handle control flow while controlling a drone? At first glance, throwing commands via setTimeout without actual acknowledge seems not so solid but you may have a different view/feedback.

Let me know!

**Comment by Mechazawa** [comment]
My plan is to change it that the promise will be resolved when it sends the command (`NON_ACK`) or when it receives an `ACK` response for a command (only some commands have this). There is no way of getting a clear drone response due to the way the protocol is designed.

I've done it using `setTimeout` in the example to easily time the commands for a quick automated test flight script.

**Comment by vvo** [comment]
Any pointers on how to do it? I am totally down to participate here

**Comment by Mechazawa** [comment]
By default commands are of the type `DATA_WITH_ACK` (see [here](https://github.com/Mechazawa/minidrone-js/blob/master/src/DroneCommand.js#L78)) but I don't wait for the ACK before sending the next command. 

I handle the `ACK` by calling a defined callback for the bluetooth channel. https://github.com/Mechazawa/minidrone-js/blob/master/src/DroneConnection.js#L250
I currently don't set the callback in the `runCommand` function. 

Protocol reference: https://developer.parrot.com/docs/SDK3/ARSDK_Protocols.pdf

**Comment by vvo** [comment]
If I understand well, the only needed changes are to listen for updates and build a queue on top of that?

The thing I don't get is that in the received buffer (in _updateSensors), I don't know how to map the message ID sent to the ack received, is that even feasible?

**Comment by vvo** [comment]
Trying to implement this, but I miss how to:
- send an ack in case of ACK_DRONE_DATA from udpateSensors, what's the message to send? The protocol is cryptic for me unfortunately
- fill in _commandCallback with the right channel at runCommand time, I can't understand how to tie the two ends, runCommand and handleIncoming

**Comment by vvo** [comment]
I found ways to achieve what I want I believe, DATA_WITH_ACK should be waited in ACK_COMMAND_SENT, but still I am wondering if it's feasible for the drone to inform me when "open claw" is really finished by just comparing sequence numbers somehow.

If not Ill just listen the right events and thats it

**Comment by Mechazawa** [comment]
>The thing I don't get is that in the received buffer (in _updateSensors)

I fear I made a mistake during a refactor. I've fixed it here 217c807ce44d17fc5cb50aa941df7df23ca8051a

>send an ack in case of ACK_DRONE_DATA from udpateSensors, what's the message to send? The protocol is cryptic for me unfortunately

The protocol is pretty cryptic yeah. It's not that well defined. I don't know how it works. I recommend referencing other implementations.

>fill in _commandCallback with the right channel at runCommand time, I can't understand how to tie the two ends, runCommand and handleIncoming

`_commandCallback` doesn't do anything at the moment if I'm not mistaken. You can change that if you want. 


I'm sorry if I'm brief at the moment but I'm currently on vacation with friends. I'll have a in-depth look at it on Monday.

**Comment by vvo** [comment]
Ok that works, I think I have a small idea on how to implement all of that in a hacky way where I don't understand everything but it works, also you can maybe voice your opinion here: http://forum.developer.parrot.com/t/feedback-on-current-state-of-parrot-sdks/7110/1

Nothing against minidrone-js, I think you are doing great and putting hard work. It's just that we should not have to do all of that to fly a programmable drone.

**Comment by Mechazawa** [comment]
Added!

**Comment by vvo** [comment]
NICE!
