### ISSUE TITLE
Examples of reading responses

### ISSUE THREAD

**Issue by vvo** [Mechazawa/minidrone-js#3]
Hi again, the library says "It supports receiving sensor updates", can you give an example of that?

Does it also support taking pictures?

**Comment by Mechazawa** [comment]
It does support taking pictures but it does not support the FTP protocol it uses at the moment. So you can take a picture using the `PictureV2` command but you'll have to download it from the drone manually using the USB cable or something. This is a planned feature. #5

`const takePicture = parser.getCommand('minidrone', 'MediaRecord', 'PictureV2');`

**Comment by Mechazawa** [comment]
The drone does not use a classical command response approach but instead it sends "commands" to the client that can be interpreted as events. It will fire an event every time a command state (sensor reading) has been updated.

See: https://github.com/Mechazawa/minidrone-js/blob/master/src/DroneConnection.js#L300

```js
connection.on('sensor:minidrone-UsbAccessoryState-GunState', sensor => {
 if (sensor.state.value === sensor.state.enum.READY) {
   console.log('The gun is ready to fire!');
 }
});
```

**Comment by vvo** [comment]
Very smart, thanks will be very useful!
