### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by NobilisNC** [Mechazawa/minidrone-js#6]
Hello,

I tried to install via npm.
But I have the current error : 

```
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: arsdk-xml@git://github.com/Parrot-Developers/arsdk-xml.git#f241e26.
npm ERR! package.json npm can't find a package.json file in your current directory.
```

So, the error cames from the XML repo ? Because there is no package.json ?

I don't know npm. So may be I just forgot something ?

**Comment by vvo** [comment]
I created arsdk-xml package to solve this

**Comment by NobilisNC** [comment]
Ok, but I still have the issue.
You did not update the package.json from minidrone to use it.

**Comment by vvo** [comment]
I am not maintaining this module, also see https://github.com/algolia/pdrone which is currently working
