### ISSUE TITLE
collaborating

### ISSUE THREAD

**Issue by vvo** [Mechazawa/minidrone-js#7]
Hey hi @Mechazawa, since I had many things to change on minidrone-js to make it work, I created pdrone: https://github.com/algolia/pdrone

Sorry there's no README for now but the goal of pdrone is to:
- have a stable low level library (basically minidrone-js but with changes)
- provide a high level library called pdrone (it wraps minidrone-js).

Starting from minidrone-js repository I:
- moved it to a monorepo architecture (https://github.com/algolia/pdrone/tree/master/src)
- removed the complete build stack (no webpack/babel etc..) because it was a LOT of code for only supporting import keyword to my POV. I prefer to have a very stable nodejs stack first and then see how to have it for browser
- fixed many small bugs in minidrone-js:
  - this._parser
  - sequence number in buffer at the right position
  - writing and reading floats in messages was broken (see https://github.com/algolia/pdrone/commit/43cc0c4150297dab97d0f0bc119b8bd551da268f)

There are many things we don't get I think in the protocol and how to handle it well.

The high level API for now is this:

```js
const pdrone = require('pdrone');
const drone = pdrone({id: 'teamx', debug: false});
drone.on('connected', function() {
  drone.flatTrim(); // use flatTrim() everytime you want the drone to calm down
  drone.takeOff();
  drone.land();  
  drone.flatTrim();
  drone.emergency(); // immediately stops the drone, that's what is inside stop.js
  drone.fly({
    roll: 0, // -100/100
    pitch: 0, // -100/100
    yaw: 0, // -100/100
    gaz: 0, // -100/100, = throttle
  });
  drone.autoTakeOff(); // will start propellers in low mode and wait for you to throw it in the air (gently)
  drone.flip({direction: 'right'}); // front/back/right/left
  drone.cap({offset: 0}); // -180/180, I have no idea what this does
  drone.openClaw();
  drone.closeClaw();
  drone.fire();

  // events
  drone.on('connected', function() {});
  // flight status, accessories, ... you'll have to dig that
  drone.on('sensor', function(event) {
    // event.name =>
    //   flatTrimDone, status, alert, claw, gun, position, speed, altitude, quaternion
    // event.value
  });
});
```

We even built some kind of loop to reconnect.

My goal with pdrone is to provide both low level and high level semantics. Let me know what you think.

**Comment by Mechazawa** [comment]
Thanks for the excellent feedback! I'll definitely implement these improvements in the library. I've also considered building a class for high-level access to the drone and I'll definitely take inspiration from your implementation.

**Comment by Mechazawa** [comment]
>We even built some kind of loop to reconnect.

Did you implement this in the high level implementation or the modified minidrone-js?

**Comment by vvo** [comment]
Inside the high level.

I believe the low level should be as simple as possible

**Comment by Mechazawa** [comment]
I implemented most of the improvements I found in pdrone. Please tell me if you notice that Imissed anything.

>removed the complete build stack (no webpack/babel etc..) because it was a LOT of code for only supporting import keyword to my POV. I prefer to have a very stable nodejs stack first and then see how to have it for browser

I understand that. I might do the same. For me it was purely for the convenience.

**Comment by vvo** [comment]
Add a quick look, this seems great! Are you having fun with your drone? :p

**Comment by Mechazawa** [comment]
Mostly been accidentally flying it into walls at high speeds. But it's great fun!

**Comment by Mechazawa** [comment]
>>removed the complete build stack (no webpack/babel etc..) because it was a LOT of code for only supporting import keyword to my POV. I prefer to have a very stable nodejs stack first and then see how to have it for browser
>
>I understand that. I might do the same. For me it was purely for the convenience.

I've removed the webpack and babel dependencies
