### ISSUE TITLE
 Non-registry package missing package.json: arsdk-xml@git://github.com/Parrot-Developers/arsdk-xml.git#f241e26.

### ISSUE THREAD

**Issue by jbarbosa29** [Mechazawa/minidrone-js#9]
I get the above error and the output log is below... any help?

33 verbose stack Error: Non-registry package missing package.json: arsdk-xml@git://github.com/Parrot-Developers/arsdk-xml.git#f241e26.
33 verbose stack     at BB.join (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\finalize-manifest.js:160:23)
33 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
33 verbose stack     at Holder$5._callFunction (eval at generateHolderClass (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\join.js:92:16), <anonymous>:14:44)
33 verbose stack     at Holder$5.checkFulfillment (eval at generateHolderClass (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\join.js:92:16), <anonymous>:29:30)
33 verbose stack     at Promise.eval (eval at thenCallback (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\join.js:14:16), <anonymous>:6:20)
33 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:566:21)
33 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
33 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
33 verbose stack     at Promise._fulfill (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:638:18)
33 verbose stack     at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\nodeback.js:42:21)
33 verbose stack     at Object.emit (events.js:185:15)
33 verbose stack     at Object.Parser.on._ (C:\Program Files\nodejs\node_modules\npm\node_modules\tar\lib\parse.js:75:14)
33 verbose stack     at Object.emit (events.js:180:13)
33 verbose stack     at Object.[emit] (C:\Program Files\nodejs\node_modules\npm\node_modules\tar\lib\parse.js:229:12)
33 verbose stack     at Object.[maybeEnd] (C:\Program Files\nodejs\node_modules\npm\node_modules\tar\lib\parse.js:338:17)
33 verbose stack     at Object.[consumeChunk] (C:\Program Files\nodejs\node_modules\npm\node_modules\tar\lib\parse.js:346:21)
34 verbose cwd C:\Users\jbarbosa\MamboDrone
35 verbose Windows_NT 10.0.16299
36 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "minidrone-js"
37 verbose node v9.11.1
38 verbose npm  v5.6.0
39 error code ENOPACKAGEJSON
40 error package.json Non-registry package missing package.json: arsdk-xml@git://github.com/Parrot-Developers/arsdk-xml.git#f241e26.
41 error package.json npm can't find a package.json file in your current directory.
42 verbose exit [ 1, true ]

**Comment by vvo** [comment]
Yep I had to publish this on npm too https://www.npmjs.com/package/arsdk-xml

**Comment by Mechazawa** [comment]
Fixed
